PVObject_=pvModule
  Version=7.4.2
  Flags=$00C00743

  PVObject_Commercial=pvCommercial
    Comment=https://www.longi.com/en/
    Flags=$0041
    Manufacturer=Longi Solar
    Model=LR5-72HBD-560M G2 Bifacial_Test
    DataSource=Manufacturer 2023
    YearBeg=2023
    Width=1.134
    Height=2.278
    Depth=0.035
    Weight=32.600
    NPieces=100
    PriceDate=06/09/23 14:53
    Remarks, Count=5
      Str_1=Frame: Aluminum
      Str_2=Structure: Heat strengthened AR glass
      Str_3=Connections: Glass-Glass, Jbox IP68, MC4 EVO2 or mateable
      Str_4=Bifacial PERC Half-cut
      Str_5
    End of Remarks
  End of PVObject pvCommercial

  Technol=mtSiMono
  NCelS=72
  NCelP=2
  NDiode=3
  SubModuleLayout=slTwinHalfCells
  FrontSurface=fsARCoating
  GRef=1000
  TRef=25.0
  PNom=560.0
  PNomTolLow=0.00
  PNomTolUp=3.00
  BifacialityFactor=0.700
  Isc=14.100
  Voc=50.10
  Imp=13.260
  Vmp=42.25
  muISC=8.46
  muVocSpec=-124.2
  muPmpReq=-0.336
  RShunt=500
  Rp_0=2000
  Rp_Exp=5.50
  RSerie=0.190
  Gamma=0.988
  muGamma=-0.0005
  VMaxIEC=1500
  VMaxUL=1500
  Absorb=0.90
  ARev=3.200
  BRev=3.200
  RDiode=0.010
  VRevDiode=-0.70
  AirMassRef=1.500
  SandiaAMCorr=50.000
  RelEffic200=-3.00
End of PVObject pvModule
